# Generated by Django 3.0.5 on 2020-05-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounts',
            name='phone',
            field=models.IntegerField(default=123456),
            preserve_default=False,
        ),
    ]
