# Generated by Django 3.0.5 on 2020-05-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200519_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default='img.jpg', upload_to='media/blog_img/'),
        ),
    ]
