# Generated by Django 3.0.5 on 2020-05-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_blogs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default='media/blog_img/img.jpg', upload_to='media/blog_img/'),
        ),
    ]
